apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana-community.github.io/helm-charts'
    chart: grafana
    targetRevision: '13.*'
    helm:
      values: |
        adminPassword: "admin"
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://prometheus-server.observability.svc.cluster.local
                isDefault: true
              - name: Loki
                type: loki
                access: proxy
                url: http://loki.observability.svc.cluster.local:3100
              - name: Jaeger
                type: jaegertracing-jaeger-datasource
                access: proxy
                url: http://jaeger.observability.svc.cluster.local:16686
        grafana.ini:
          plugins:
            preinstall_sync: >-
              jaegertracing-jaeger-datasource@0.4.1@https://github.com/jaegertracing/grafana-plugin/releases/download/v0.4.1/jaegertracing-jaeger-datasource-0.4.1.zip
            allow_loading_unsigned_plugins: jaegertracing-jaeger-datasource
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
